### ISSUE TITLE
Below Murphys Powerhouse (MIF) schematic & logic

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#14]
This IFR has not been included. However, Murphys PH is a node.  If you choose to add this, I suggest using 11298650, "Angels Creek below Murphys Afterbay", as the reference gauge.

**Comment by rheinheimer** [comment]
@alanccai This is great! I was struggling with Murphy's PH flow, since it has operated historically as (or some variation of this):
![image](https://user-images.githubusercontent.com/9124277/68626011-0eee5400-04a0-11ea-9692-0eafbcdb4b2e.png)

This IFR is probably the answer I was looking for.

**Comment by rheinheimer** [comment]
Yes, this IFR is exactly what's missing. From the following, the above observed flow maches with a Normal/Wet WY
![image](https://user-images.githubusercontent.com/9124277/68626451-02b6c680-04a1-11ea-8b2f-fbe8c3e42764.png)

**Comment by rheinheimer** [comment]
Note to self: Currently, the per-catchment summation for year type calculation for the planning model is:
`runoff = self.model.parameters['STN_{:02} Headflow/1'].dataframe[start:end].sum()`
This is incorrect and needs to be updated.

**Comment by rheinheimer** [comment]
This IFR at Murphys Park (just upstream of Angels PH div) is now working beautifully. Just need some little tweaks (factor of safety typically applied to IFRs by operators, which you can see here)

![image](https://user-images.githubusercontent.com/9124277/69018404-ef5c9d00-0971-11ea-8306-514f4bcf9d65.png)

**Comment by GustavoFacincani** [comment]
The only difference I found from the text to the pseudocode was for WYT classification according to the unimpaired inflow: Dryest = only equal 140,000 (not greater or equal). 2nd Driest WY = equal or greater than 140,001 (not 140,000).
