### ISSUE TITLE
IFR Below Pinecrest Lake

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#15]
Currently STN_24 Headflow comes in between the IFR node and the USGS gauge.  Do some moving around so they are adjacent?

**Comment by rheinheimer** [comment]
Same logic as #16. Correct as is.

![image](https://user-images.githubusercontent.com/9124277/68625803-9c7d7400-049f-11ea-9b23-9c3dd2dc37f1.png)
