### ISSUE TITLE
IFR bl Relief Resersvoir

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#16]
Currently STN_20 Headflow comes in between the IFR node and the USGS gauge.  Do some moving around so they are adjacent?

**Comment by rheinheimer** [comment]
Correct as is. Gauge & STN_20 are at the catchment outlet, which is correct. The IFR is below the reservoir, so should be upstream, just below the Relief Reservoir catchment. Also note that there is no routing in this model, so distance between nodes doesn't matter (for now).

![image](https://user-images.githubusercontent.com/9124277/68625551-09443e80-049f-11ea-9915-3b8896a3d14f.png)
