### ISSUE TITLE
IFR bl Sand Bar Div

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#17]
I think the sequencing in this stretch may be slightly incorrect.  According to the USGS schematic, from upstream to downstream, it should be: (1) Beardsley Lake, (2 )Beardsley PP,   (3) Sand Bar PP, (4) Philadelphia Canal joins the MFSR, (4) Stanislaus   Tunnel, (5) IFR node.  Currently, looks   like (3) and (4) are out of order and should be flipped.  Otherwise, looks good.

Please see: https://ca.water.usgs.gov/data/waterdata/Schematics2010/stanislaus.r.basin.pdf.  note that "Sand Bar PP" is labelled as "JW Southern Powerplant" in the schematic

**Comment by rheinheimer** [comment]
I looked into this previously, and basically concluded that the USGS schematic is incorrect. The JW Southern Powerplant (aka Sand Bar) is downstream of Spring Gap PP. No change.

**Comment by rheinheimer** [comment]
fyi, here's a good source for the MF Stan hydropower: https://play.google.com/books/reader?id=sO00AQAAMAAJ&printsec=frontcover&pg=GBS.PA141

Therein, there's a fuzzy-resolution schematic:

![image](https://user-images.githubusercontent.com/9124277/68625297-64296600-049e-11ea-9e3b-6601c0ee8656.png)

**Comment by GustavoFacincani** [comment]
The differences I found between the pseudocode and the text are: Minimum supplemental flow -> Week 6 = 140 (instead of 125), Week 7 = 220 (instead of 200), Week 8 = 400 (instead of 325), Week 9 = 180 (instead of 175), Week 10 = 110 (instead of 95), Week 11 = 65 (instead of 55).
