### ISSUE TITLE
IFR Confluence of NF and Beaver Creek

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#20]
IFR   node should be moved to be directly adjacent to USGS Gauge 11295300?  Currently, "STN_05 Inflow" comes   in between them.  Or, perhaps STN_05   should be moved to be downstream from the gauge and the IFR--

**Comment by rheinheimer** [comment]
@alanccai I might have corrected this before you spotted it. Does this look okay?
![image](https://user-images.githubusercontent.com/9124277/68722899-94473680-057c-11ea-8750-3aff04d0d693.png)

**Comment by alanccai** [comment]
@rheinheimer  Looks good.
