### ISSUE TITLE
IFR bl Don Pedro Reservoir

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#21]
The USGS gauge for this IFR (11289650) is not part of the network, but could be added in.

**Comment by GustavoFacincani** [comment]
The only thing that doesn't match in the pseudocode was WYT classification according to the unimpaired inflow: Dry = only greater than 350,000 (not greater or equal). Normal = only greater than 676,000 (not greater or equal).

**Comment by rheinheimer** [comment]
This is now in the network
