### ISSUE TITLE
Below Balsam Meadows Forebay

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#22]
Balsam Meadows Forebay, 5000 a-f of storage, is missing from the OpenAgua Network.  Please  see the schematic for a visual depiction of where it would go: https://ca.water.usgs.gov/data/waterdata/Schematics2010/s.joaquin.low.r.basin.pdf

**Comment by rheinheimer** [comment]
It was actually there, just not explitly labelled as such. See #23, as it's related to Eastman PP.

**Comment by rheinheimer** [comment]
@alanccai Is this for the IFR or the forebay?

**Comment by rheinheimer** [comment]
Okay, I just added both the IFR and USGS gauge to the schematic.
