### ISSUE TITLE
SFSJR Below Confluence with Hooper Creek (IFR)

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#23]
In   OpenAgua, there is a  IFR node is   located directly downstream of Florence Lake, however, according to   "Initial Information Package for the Big Creek Hydroelectric System   (2000)" this IFR is actually located on the SFSJR below its confluence   with Hooper Creek, and is gauged by USGS 11230215.          I could not find Hooper Creek in the OpenAgua network.  USGS Gauge 11230215 is not there   either.

Please see the USJ schematic for a visual depiction: https://ca.water.usgs.gov/data/waterdata/Schematics2010/s.joaquin.up.r.basin.pdf

Please also see the Initial Information Package for the Big Creek Hydroelectric System   (2000) document, page 70: https://www1.sce.com/nrc/bigcreek/2000_IIP.pdf

**Comment by rheinheimer** [comment]
Okay, I think all is good now. We don't have Hooper Cr. explicitly, but SJN_37 includes Hooper Cr. I've updated the schematic accordingly. Note that there's also a newer gauge (11230070) a bit closer to Florence Lake as well, which I've added.

@alanccai Can you just confirm that, based on your research, there is definitely no IFR right below Florence Lake?

![image](https://user-images.githubusercontent.com/9124277/68736382-1e57c500-05a6-11ea-8fba-3ee8aa6368f4.png)

**Comment by alanccai** [comment]
Just this:

![image](https://user-images.githubusercontent.com/35709110/68739665-30356a00-059e-11ea-8da5-19c062468f2f.png)

(A maximum IF, as opposed to a MIF)

**Comment by rheinheimer** [comment]
Interesting, so that is a maximum flow, not a minimum flow. I've created #38 to address this, and am closing this issue.
