### ISSUE TITLE
Below Hooper Creek Diversion (MIF)

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#24]
Would   require adding Hooper Creek to the network, which isn't there currently.

**Comment by rheinheimer** [comment]
@alanccai Do you have more info about the diversion? Could you post a screenshot of a relevant schematic? I doubt we will add anything, but it will be useful to have the info.

**Comment by rheinheimer** [comment]
Based on p. 70 footnote of the 2000_IIP.pdf doc:
> (2) Included in So. Fk. San Joaquin River below Hooper.
I'm going to close this. @alanccai nothing more needed.
