### ISSUE TITLE
Below Lake Thomas A. Edison schematic

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#26]
Not there, can be added into the current network.

**Comment by rheinheimer** [comment]
@alanccai Can you please clarify? What isn't there? An IFR? There is and IFR below the Mono Cr. diversion.

![image](https://user-images.githubusercontent.com/9124277/68734189-0cbeef00-059f-11ea-8863-ecc13af58f82.png)

**Comment by alanccai** [comment]
![image](https://user-images.githubusercontent.com/35709110/68737913-b7ccaa00-0599-11ea-9cba-69f00ba4d9d4.png)
From the 2000 SCE document.  

The IFR below the Mono Cr. diversion you're referring to above is a separate IFR that's part of FERC # 67, Big Creek 2A, 8 & Eastwood

**Comment by rheinheimer** [comment]
Thanks, added it.
