### ISSUE TITLE
IFR bl Big Creek 6 Div

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#28]
The USGS Gauge for this IFR,   11238600, isn't currently in the network, but could be added.

Also, FYI, Other   sources refer to this as "Below Dam 6".

**Comment by rheinheimer** [comment]
@alanccai Note that this is in the middle of one of our subcatchments, where we don't have adequate hydrological representation. Not adding.

![image](https://user-images.githubusercontent.com/9124277/68733520-8e614d80-059c-11ea-9ad4-d8f301f33123.png)
