### ISSUE TITLE
Below Chilkoot Lake

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#29]
Missing.  Would   require adding Chilkoot Lake to the network.

**Comment by rheinheimer** [comment]
As far as I can tell, this is a small remote lake. @alanccai any more info?

![image](https://user-images.githubusercontent.com/9124277/68732044-b306f680-0597-11ea-88e9-faaa91d5953d.png)

**Comment by alanccai** [comment]
"Article 404: Releases from Chilkoot Lake. The licensee shall operate the project such that release flows from Chilkoot Lake shall not exceed 15 cubic feet per second, in order to reduce erosion and protect water quality and riparian habitat downstream of Chilkoot Lake."

**Comment by alanccai** [comment]
Outflows from Chilkoot Lake into Chilkoot Creek, which joins North Fork Willow Creek.

https://california.hometownlocator.com/maps/feature-map,ftc,1,fid,258283,n,chilkoot%20creek.cfm.

IFR related to Crane Valley Project (FERC No. 1354).

**Comment by alanccai** [comment]
![image](https://user-images.githubusercontent.com/35709110/68783293-9b5b5c80-05ef-11ea-908a-7374d968d1f9.png)
 This is pasted from the 2003 License for Crane Valley Project (P-1354)

**Comment by rheinheimer** [comment]
We are not including operations in this region, so closing.
