### ISSUE TITLE
Cannot get real time inflow to reservoirs

### ISSUE THREAD

**Issue by asood12** [vicelab/sierra-pywr#3]
For some IFR calculations, we need to get inflow in the same timestep, which is not directly possible using the base Pywr setup.

**Comment by rheinheimer** [comment]
Would it be possible to add a conveyance around the reservoir with a capacity of whatever the minimum flow requirement is? I.e., any IFR would necessarily bypass the storage, and any IFR unmet due to inflow constraints would not be released by the reservoir.

**Comment by rheinheimer** [comment]
This is impossible without some kind of inter-step submodel. For now, without greater specificity, such as an example where this is a problem, this issue does not seem worth keeping open.
