### ISSUE TITLE
IFR bl San Joaquin 1A Div

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#30]
SJN_08   Headflow  is placed in between the IFR   node and the USGS gauge, it or the IFR node should be moved.

**Comment by rheinheimer** [comment]
Link to location: https://www.openagua.org/network/1/1201/1224/724/network/map?lat=38.18259346&lng=-120.16100036&tiles=Google%2520Terrain&zoom=16

**Comment by rheinheimer** [comment]
@alanccai Is this about the Willow Creek gauge? It looks okay to me. It's not for the IFR.

![image](https://user-images.githubusercontent.com/9124277/68724673-c6a76280-0581-11ea-8066-fd8038ca63d6.png)

**Comment by alanccai** [comment]
![image](https://user-images.githubusercontent.com/35709110/68736898-cbc2dc80-0596-11ea-819a-0d562ad06811.png)

**Comment by alanccai** [comment]
![image](https://user-images.githubusercontent.com/35709110/68736936-e7c67e00-0596-11ea-9cc8-74b44ccb99af.png)

**Comment by alanccai** [comment]
If you believe the USGS schematic, I think this is where the IFR node would go:

![image](https://user-images.githubusercontent.com/35709110/68737205-98348200-0597-11ea-9ecf-42c71f8929e4.png)

**Comment by alanccai** [comment]
Sorry, looks like my original comment about SJN_08 Headflow was off.

Basically, shift the "IFR bl San Joaquin 1 Div" Node to be between those two closely spaced black dots... and maybe rename the IFR to be "IFR bl San Joaquin 1A Div" or "IFR bl South Fork Willow Creek Diversion" because that's more accurate.  My bad.

**Comment by rheinheimer** [comment]
Yes, got it. Thanks. See changes:

![image](https://user-images.githubusercontent.com/9124277/68738736-b48ee980-05ac-11ea-954b-a622572484f0.png)

**Comment by rheinheimer** [comment]
Note that this still doesn't address the issue of gauges. As far as I can tell, there are no gauges below the two IFRs in Willow Cr. and NF Willow Cr. in the above region. @alanccai can you confirm?

**Comment by alanccai** [comment]
There is no gauge that I could find.

**Comment by rheinheimer** [comment]
Good enough for me.
