### ISSUE TITLE
IFR bl Mammoth Pool Reservoir

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#31]
SJN_20  Headflow is placed in between the IFR node and the USGS gauge, should be moved.

**Comment by rheinheimer** [comment]
Correct as is.

**Comment by rheinheimer** [comment]
I was wrong about being correct. After reading the 2000_IIP.pdf document, I've revised this as:

![image](https://user-images.githubusercontent.com/9124277/68737814-34678480-05aa-11ea-98be-b5e958851560.png)
