### ISSUE TITLE
USGS Gauges measuring IFRs that could be added

### ISSUE THREAD

**Issue by alanccai** [vicelab/sierra-pywr#32]
The following IFRs have USGS gauges associated with them, but those gauges aren't currently in the model.

[Copy of USGS.Gauges.for.IFRs.in.USJ.xlsx](https://github.com/vicelab/sierra-pywr/files/3833433/Copy.of.USGS.Gauges.for.IFRs.in.USJ.xlsx)

**Comment by rheinheimer** [comment]
We'll add these and include with #37

**Comment by rheinheimer** [comment]
@alanccai Please note for your records: USGS 11238500 BIG C NR MOUTH NR BIG CREEK CA is lower down, below SJN_24, not just for the Big Creek 5 Div IFR above it.

I'm closing this issue since the gauges have been added, and the gauges are listed in #37.
