### ISSUE TITLE
add IFR below Thomas A Edison logic

### ISSUE THREAD

**Issue by rheinheimer** [vicelab/sierra-pywr#42]
See #26. Data needs to be populated. IFR is a constant 10 cfs.

**Comment by GateauXD** [comment]
What branch has the updated JSON file with this IFR? I can't seem to find it on master or optimization branch.

**Comment by rheinheimer** [comment]
@GateauXD You can add this directly to the OpenAgua interface

**Comment by GateauXD** [comment]
Added on OA.
