### ISSUE TITLE
need to check that appropriate WYTs are applied to IFRs

### ISSUE THREAD

**Issue by rheinheimer** [vicelab/sierra-pywr#64]
Right now, most, if not all, IFRs use the SJVI for WYTs. I don't think this is appropriate; need to check & update as needed.

**Comment by alanccai** [comment]
Gustavo and I have updated the google sheet with all the parameters you might need to create site-specific WYT classification methods:


1. Water Year Type classification - Based on inflows at what location?
2. Water Year Type classification - what month(s) are the forecast(s) made?
3. Who is making the forecast - Bureau of Reclamation, CA Department of Water Resources, or Other?
4. Is the forecast made of April-July runoff or the annual runoff?  Or other?
5. Once the forecast is made, how long is it valid for?

Note the unusually complex method for Friant Dam.
Also note the license documents' lack of specification of some of these attributes in some cases.  We will leave it up to you to choose a method in those cases.

**Comment by asood12** [comment]
For Stanislaus:
Below Donnells, Below Sand Bar, Below Philadelphia Diversion, Below Relief Res, Below Pinecrest Lake, and Below Sand Bar use the following for WYT:

Water Year Type | DWR Forecast Annual   Unimpaired Inflow to New Melones Reservoir (acre-feet)
-- | --
Critically Dry | Less than or equal to 350,000
Dry | Greater than 350,000 and less   than or equal to 676,000
Normal | Greater than 676,000 and less   than 1,585,000
Normal-Dry | Greater than 676,000 and less   than 1,050,000
Normal-Wet | Greater than or equal to   1,050,000 and less than 1,585,000
Wet | Greater than or equal to   1,585,000

Created a csv file - "stanislaus_WYT.csv", which gives WYT: 1 - Critically dry, 2 - Dry, 3 - Normal Dry, 4 - Normal Wet, 5 - Wet

**Comment by alanccai** [comment]
[Stanislaus River WYT classification parameters.docx](https://github.com/vicelab/sierra-pywr/files/3894733/Stanislaus.River.WYT.classification.parameters.docx)

**Comment by alanccai** [comment]
@asood12  your table above isn't quite right for Below Donnells Reservoir - that IFR has one less Water Year Type category - please see my word doc.  But it's correct for all the others IFRs you listed.

**Comment by asood12** [comment]
@alanccai - one less category is because they have merged "Normal-Dry" and "Normal-Wet" into a single category of "Normal".

**Comment by alanccai** [comment]
Hi Aditya - yes, that's correct, but wouldn't that affect the numbering?  Would it be better to have two separate csv files, one with the merged and one without?

**Comment by alanccai** [comment]
Hi Aditya, you're right - it would be simple to code that situation.

**Comment by alanccai** [comment]
[USJ WYT classification parameters.docx](https://github.com/vicelab/sierra-pywr/files/3898657/USJ.WYT.classification.parameters.docx)

**Comment by alanccai** [comment]
[Merced WYT classification parameters.docx](https://github.com/vicelab/sierra-pywr/files/3898713/Merced.WYT.classification.parameters.docx)

**Comment by alanccai** [comment]
[Tuolumne WYT classification parameters.docx](https://github.com/vicelab/sierra-pywr/files/3898769/Tuolumne.WYT.classification.parameters.docx)

**Comment by GateauXD** [comment]
Added WYT 2019 and WYT 2130 for Stan

See: https://github.com/vicelab/sierra-pywr/commit/afda652745d5fd31366c4ad64e8faa56e7de84cc

**Comment by rheinheimer** [comment]
Here is an updated list of corrections that are needed:

3 IFRs use the SJI:
IFR_bl_Beardsley_Afterbay_Min_Requirement
IFR_bl_Lyons_Res_Requirement
IFR_bl_Browns_Creek_Ditch_Min_Flow

**Comment by rheinheimer** [comment]
Follow-up notes:

- IFR below Beardsley Afterbay: the language is vague, but for now we can assume it refers to the SJI. See #62.
- IFR below Lyons: DWR year type is referenced, and again it is assumed this is SJI.
- IFR below Browns Creek Ditch appears correct
