### ISSUE TITLE
Instream flow requirement (IFR) accuracy check

### ISSUE THREAD

**Issue by rheinheimer** [vicelab/sierra-pywr#9]
This issue is to document checking instream flow requirements with actual code. I.e., the code in each of the basin models should reflect what the IFR actually is.

**Comment by GateauXD** [comment]
Related Issue:
https://github.com/vicelab/sierra-pywr/issues/41

**Comment by GustavoFacincani** [comment]
IFR Below Angels Diversion dam [also called Utica Ditch Diversion Dam]: I believe that the flushing rate that is missing is found on page 37: "The verification of flushing flows shall be from the existing streamflow gage in Angels Creek below the Angels diversion dam (S-124), which will be rated as a minimum for flows up to 14 cfs".

**Comment by GustavoFacincani** [comment]
IFR Below Beaver Creek Diversion Dam: If ramping rates are to be considered, this is what is found on article 50: "Licensee shall operate the project in such a manner as not to cause fluctuations in the stream greater than one foot per hour, downstream of each project discharge facility."

**Comment by GustavoFacincani** [comment]
Below Donnells Reservoir: For WYT classification according to the unimpaired inflow: Dry = only greater than 350,000 (not greater or equal). Normal = only greater than 676,000 (not greater or equal).

**Comment by GustavoFacincani** [comment]
IFR below La Grange Diversion Dam: not all numbers in the pseudocode match the SJ index (use SJ index numbers instead!).

**Comment by GustavoFacincani** [comment]
IFR below Murphys Powerhouse: For WYT classification according to the unimpaired inflow: Dryest = only equal 140,000 (not greater or equal). 2nd Driest WY = equal or greater than 140,001 (not 140,000).

**Comment by GustavoFacincani** [comment]
IFR below O'Shaughnessy Dam: A minimal difference from document: March 1-31, condition: if precipitation is >18.6 (not 18).

**Comment by GustavoFacincani** [comment]
IFR below Sand Bar Diversion Dam: Minimum supplemental flow -> Week 6 = 140 (instead of 125), Week 7 = 220 (instead of 200), Week 8 = 400 (instead of 325), Week 9 = 180 (instead of 175), Week 10 = 110 (instead of 95), Week 11 = 65 (instead of 55).

**Comment by GustavoFacincani** [comment]
Don Pedro Reservoir: Minimum pool is 550, not 600, according to the following: Article 403.  Minimum Pool at Don Pedro Reservoir.  The licensees must maintain a minimum pool elevation in Don Pedro Reservoir of not less than 550 feet National Geodetic Vertical Datum of 1929, except for drawdowns necessary to maintain minimum streamflows specified in article 409 (Minimum Flows below La Grange Diversion Dam).

**Comment by rheinheimer** [comment]
This issue is somewhat nebulous. Closing
