### ISSUE TITLE
McSwain and Merced Falls PH specs

### ISSUE THREAD

**Issue by GustavoFacincani** [vicelab/sierra-pywr#93]
McSwain and Merced Falls PH are missing specifications. Here they are:

**McSwain**
Water Surface Elevation (WSE) head (or, rated head on turbine) = 54 feet
Flow capacity in WSE = 2,700 cfs

**Merced Falls**
WSE Head = 26 feet (but a FERC draft EIS says the max height of the dam is 34 feet)*
Flow capacity in WSE = 1,750 cfs

_Reference (Page 62)_
https://www.waterboards.ca.gov/waterrights/water_issues/programs/bay_delta/docs/sed/app4a_all/4A-Ltrs/WQCP1_1166_dennis_herrera(REV)_Pt%204.pdf

*WSE head confirmed to be 26 feet here (page 15): 
"In contrast, an acre-foot of water passing through Pacific Gas and Electric Company’s
low head **Merced Falls Project with 26 feet of drop between the forebay and tailrace** would produce only 24 kWh of electrical energy." 
https://www.cpuc.ca.gov/environment/info/aspen/pgehydro/DEIR%20Files/Appendix%20B.pdf

**Comment by rheinheimer** [comment]
This has been incorporated into the model.
